# Generated by Django 2.2.12 on 2020-11-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_auto_20201119_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kelompok_id',
            new_name='kelompok',
        ),
    ]
